#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V

feh --bg-fill /home/ravi/Downloads/wallpaper.png

bspc config border_width         1
bspc config window_gap           2
bspc config top_padding          29

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc rule -a xfce4-appfinder --collapsed state=floating

xfce4-panel &
